language: python

python:
    - 2.7
    - 3.5

install: 
    - pip install -r requirements.txt
#     - pip install codecov

before_script:
  - "make run-background"  # run gunicorn server
  - sleep 10  # # give Web server some time to bind to sockets, etc

script: make test-api

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always